# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats: html

python:
   version: 3.7
   install:
      - method: pip
        path: .
        extra_requirements:
           - asyncio
           - synchronous
