version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/async-service

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

      - run:
          name: install tox
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox

      - save_cache:
          paths:
            - ./venv
            - .tox

          key: v1-dependencies-{{ checksum "setup.py" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox

workflows:
  version: 2
  build_test:
    jobs:
      - build
